"""Regenerate public JSON Schema from the actual validated runtime contracts."""

import json
from pathlib import Path
from easyagent.contracts import Workflow, AgentConfig, ToolSpec, ModelRequest, ModelResult
from easyagent.extension_contracts import (
    ExtensionManifest,
    ExtensionPackage,
    ExtensionRequest,
    ExtensionResponse,
)
from easyagent.sessions import ConversationCreate, ConversationInput
from easyagent.code_development import CodeCandidate
from easyagent.goals import GoalSpec, Repair, Verdict
from easyagent.skill_packages import SkillPackage, SkillInstall
from easyagent.backends import BackendContribution
from easyagent.connections import Connector
from easyagent.system_notifications import NotificationDevice, NotificationReceipt
from easyagent.workspace_chat import DispatchDecision
from easyagent.workflow_calls import WorkflowCall
from easyagent.nodes import NodeDefinition
from easyagent.components import ComponentManifest
from easyagent.component_packages import ComponentPackage

root = Path(__file__).resolve().parents[1] / "docs" / "contracts"
root.mkdir(parents=True, exist_ok=True)
contracts = {
    "node-definition": NodeDefinition,
    "component-manifest": ComponentManifest,
    "component-package": ComponentPackage,
    "workflow-call": WorkflowCall,
    "dispatch-decision": DispatchDecision,
    "connector": Connector, "notification-device": NotificationDevice,
    "notification-receipt": NotificationReceipt,
    "goal-spec": GoalSpec, "goal-repair": Repair, "goal-verdict": Verdict,
    "skill-package": SkillPackage, "skill-install": SkillInstall, "backend-contribution": BackendContribution,
    "code-candidate": CodeCandidate,
    "extension-manifest": ExtensionManifest,
    "extension-package": ExtensionPackage,
    "extension-request": ExtensionRequest,
    "extension-response": ExtensionResponse,
    "workflow": Workflow,
    "agent-config": AgentConfig,
    "tool-spec": ToolSpec,
    "model-request": ModelRequest,
    "model-result": ModelResult,
    "conversation-create": ConversationCreate,
    "conversation-input": ConversationInput,
}
for name, contract in contracts.items():
    schema = {"$schema": "https://json-schema.org/draft/2020-12/schema", **contract.model_json_schema()}
    (root / (name + ".schema.json")).write_text(json.dumps(schema, ensure_ascii=False, indent=2) + "\n")
print(f"Exported {len(contracts)} public contracts to {root}")

# Generate TypeScript shapes from these schemas so the SDK cannot silently drift.
named = {}
for contract in contracts.values():
    raw = contract.model_json_schema()
    for name, definition in raw.get("$defs", {}).items():
        if name in named and named[name] != definition:
            raise ValueError("Conflicting schema name: " + name)
        named[name] = definition
    named[contract.__name__] = {k: v for k, v in raw.items() if k != "$defs"}


def typescript(spec):
    if "$ref" in spec:
        return spec["$ref"].rsplit("/", 1)[1]
    if "const" in spec:
        return json.dumps(spec["const"])
    if "enum" in spec:
        return " | ".join(json.dumps(v) for v in spec["enum"])
    if "anyOf" in spec or "oneOf" in spec:
        return " | ".join(typescript(s) for s in spec.get("anyOf", spec.get("oneOf", [])))
    kind = spec.get("type")
    if isinstance(kind, list):
        return " | ".join(typescript({**spec, "type": k}) for k in kind)
    if kind == "array":
        return f"Array<{typescript(spec.get('items', {}))}>"
    if kind == "object":
        fields = spec.get("properties", {})
        if not fields:
            additional = spec.get("additionalProperties", True)
            return (
                "Record<string, never>"
                if additional is False
                else "Record<string, " + typescript(additional if isinstance(additional, dict) else {}) + ">"
            )
        parts = [
            json.dumps(k) + ("" if k in spec.get("required", []) else "?") + ": " + typescript(v) + ";"
            for k, v in fields.items()
        ]
        if spec.get("additionalProperties") is not False:
            parts.append("[key: string]: unknown;")
        return "{ " + " ".join(parts) + " }"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


output = root.parents[1] / "sdk/javascript/contracts.d.ts"
output.write_text(
    "// SPDX-FileCopyrightText: 2026 EasyAgent contributors\n"
    "// SPDX-License-Identifier: Apache-2.0\n\n"
    "// Generated by scripts/export_contracts.py; do not edit by hand.\n"
    + "".join(
        "export type " + name + " = " + typescript(schema) + ";\n" for name, schema in sorted(named.items())
    )
)
print(f"Generated {len(named)} TypeScript contracts")
